/**
 * ZONEXA — Reference data
 * Zoneware Limited
 *
 * Derived from the Project Management SOP, Version 1, September 2026.
 * STAGE_REFERENCE: [step, module, task, responsible]
 * DOC_REFERENCE:   [section, document name, tranche]
 */

var STAGE_REFERENCE = [
  ["1.1", 1, "Extract approved annual capital expenditure budgets (Lagos State MDAs + Federal ministries)", "PM"],
  ["1.2", 1, "Present MDA targeting recommendation at the Annual Strategy Call", "PM / MD"],
  ["2.1", 2, "Tender identified (selective invitation received OR opportunity flagged on PPA Portal)", "PM"],
  ["2.2", 2, "Lead Project Manager formally assigned by MD", "MD"],
  ["2.3", 2, "Bid submission approach confirmed and approved by MD", "MD"],
  ["2.4", 2, "Company PPA registration and tax profile verified for the contract class", "PM / Admin"],
  ["2.5", 2, "Payment Advice collected from MDA Accounts Unit", "PM"],
  ["2.6", 2, "Bid document purchase fee paid via Payer ID; teller/receipt obtained", "Accounts"],
  ["2.7", 2, "Technical specifications & unpriced BOQ acquired", "PM"],
  ["2.8", 2, "Bid Bond secured via LASACO Assurance", "Admin"],
  ["2.9", 2, "Full bid document package assembled (Reference A — 11 items)", "PM / Admin"],
  ["2.10", 2, "Tender uploaded to PPA Portal + physical package submitted to Ministerial Procurement Unit", "PM"],
  ["2.11", 2, "E-procurement acknowledgment email received & filed", "PM"],
  ["2.12", 2, "Evaluation tracked with Ministerial Procurement Unit through to Notification of Award", "PM"],
  ["3.1", 3, "Notification / Letter of Award followed up and collected", "PM"],
  ["3.2", 3, "Formal Letter of Acceptance submitted on company letterhead", "Admin"],
  ["3.3", 3, "Letter of Authorization (LASG/STO statutory deduction at source) submitted", "Admin"],
  ["3.4", 3, "Evidence of tax & stamp duty payment submitted", "Accounts"],
  ["3.5", 3, "Letter of Request for Advance Payment submitted to Head of Procurement", "Admin"],
  ["3.6", 3, "Banking details, Tax Clearance Certificate & Director ID submitted", "Accounts"],
  ["3.7", 3, "Advance Payment Guarantee (APG) & Performance Bond obtained via LASACO", "Admin"],
  ["3.8", 3, "Undated company security cheque executed for mobilization sum", "Accounts"],
  ["3.9", 3, "Full payment file submitted to Ministry Accounts", "Admin"],
  ["3.10", 3, "Payment Voucher raised by Ministry Accounts", "Ministry"],
  ["3.11", 3, "Resident Internal Audit compliance check passed", "Ministry"],
  ["3.12", 3, "Permanent Secretary / Executive sign-off obtained", "Ministry"],
  ["3.13", 3, "Central Internal Audit (CIA) clearance obtained", "Ministry"],
  ["3.14", 3, "Advance Payment received from State Treasury Office (STO)", "Accounts"],
  ["4.1", 4, "Awarded drawings, BOQ & specifications reviewed against tender documents", "PM / Engineer"],
  ["4.2", 4, "Project-specific risks identified with mitigation notes", "PM / Engineer"],
  ["4.3", 4, "Feasibility check run on awarded timeline & budget", "PM / Engineer"],
  ["4.4", 4, "Project plan & execution timeline developed; labor/machinery/materials allocated", "PM"],
  ["4.5", 4, "Working cost breakdown by trade package prepared (budget baseline)", "PM"],
  ["4.6", 4, "Subcontractor scope agreements executed (where applicable)", "PM"],
  ["4.7", 4, "Official site handover attended with Supervising Committee / Ministry Engineers", "PM / Engineer"],
  ["4.8", 4, "BEFORE media captured (photos/video) and archived to BEFORE_INSPECTION_LOG", "Engineer"],
  ["4.9", 4, "In-house engineer true-quantity audit of BOQ completed", "Engineer"],
  ["4.10", 4, "Trade packages split (structural core vs. internal trade sourcing)", "PM"],
  ["4.11", 4, "Competing vendor quotations gathered (≥ 2 per trade package) & compared", "PM / Admin"],
  ["4.12", 4, "Vendors/tradesmen bound to fixed-cost agreements; deposits paid; materials mobilized", "PM / Admin"],
  ["5.1", 5, "Project WhatsApp group created (Lead, Engineer, Procurement Officer, Admin observers)", "PM"],
  ["5.2", 5, "Branded safety gear issued to workers & supervisors", "Admin"],
  ["5.3", 5, "Written approval-to-proceed requested at each major execution stage & filed", "PM / Engineer"],
  ["5.4", 5, "Daily Site Log submitted to project channel (ongoing)", "Engineer"],
  ["5.5", 5, "Weekly PM site visit conducted", "PM"],
  ["5.6", 5, "Weekly Project Review held every Monday — budget vs. actual, timeline", "PM"],
  ["5.7", 5, "Monthly Executive Report submitted to MD", "PM"],
  ["5.8", 5, "Letter of Request for Contingency submitted where scope/cost/time overrun (as needed)", "PM"],
  ["5.9", 5, "Change order approved by Project Lead before variance proceeds (as needed)", "PM"],
  ["5.10", 5, "DURING media captured continuously (rebar, pours, MEP rough-ins)", "Engineer"],
  ["6.1", 6, "Internal pre-snag walkthrough & audit completed (PM + Engineer)", "PM / Engineer"],
  ["6.2", 6, "Finish flaws/defects rectified; site cleaned to pristine condition", "PM"],
  ["6.3", 6, "Ministry supervisory inspection held; punch-list signed off", "PM"],
  ["6.4", 6, "Snags resolved within 48–72 hours", "PM"],
  ["6.5", 6, "AFTER media captured", "Engineer"],
  ["6.6", 6, "Completion Notification submitted to MEPB / Budget Department", "Admin"],
  ["6.7", 6, "MEPB Budget Inspection Team escorted on-site", "PM"],
  ["6.8", 6, "MEPB Certification of Work Completed obtained", "PM"],
  ["6.9", 6, "Final submission checklist assembled (balance request, BEFORE/DURING/AFTER report, upgraded PPA cert, bank details, TIN)", "Admin"],
  ["6.10", 6, "Final balance payment routed to disbursement (MEPB → Chairman/Director → Central Procurement → Technical & Planning → Accounts)", "Accounts"],
  ["6.11", 6, "6-month retention / defect-liability monitoring begins", "PM"],
  ["6.12", 6, "Retention inspections completed at Months 1, 3 & 5", "Engineer"],
  ["6.13", 6, "Any emerging defects rectified before final Budget Team inspection", "PM"],
  ["6.14", 6, "Final joint walk with Budget Team completed; retention fund released — PROJECT CLOSED", "PM"]
];

var DOC_REFERENCE = [
  ["A", "Formal Letter of Bid signed by MD", ""],
  ["A", "Completed, priced Bill of Quantities (BOQ)", ""],
  ["A", "LASACO Bid Bond Certificate", ""],
  ["A", "CAC Certificate of Incorporation and MEMART", ""],
  ["A", "Current PPA Registration Certificate (matching class category)", ""],
  ["A", "Current Tax Clearance Certificates (company + 2 directors)", ""],
  ["A", "Evidence of 3-year Lagos State Development Levy payments", ""],
  ["A", "Company brochure, staff CVs, and equipment ownership schedules", ""],
  ["A", "Past Letters of Award and Practical Completion Certificates", ""],
  ["A", "Audited financial statements", ""],
  ["A", "Bank Letter of Credit (where requested)", ""],
  ["B", "Formal Letter of Acceptance (company letterhead)", ""],
  ["B", "Letter of Authorization — LASG/STO statutory deduction at source", ""],
  ["B", "Evidence of tax & stamp duty payment", ""],
  ["B", "Letter of Request for Advance Payment", ""],
  ["B", "Verified bank details, Tax Clearance Certificate, Director ID", ""],
  ["B", "LASACO Proposal Form (signed)", ""],
  ["B", "Counter-Guarantee Form (executed by company directors)", ""],
  ["B", "CAC Certificate of Incorporation + MEMART (copy)", ""],
  ["B", "Three-year company Tax Clearance Certificate", ""],
  ["B", "Personal tax clearances + 3-yr Development Levy receipts (2 directors)", ""],
  ["B", "Notification / Letter of Award (copy)", ""],
  ["B", "Priced BOQ or technical summary", ""],
  ["B", "Passport photographs and valid photo ID (2 directors)", ""],
  ["B", "Company utility bill (issued within last 3 months)", ""],
  ["B", "Evidence of past performance (completion certificates, past awards)", ""],
  ["B", "Signed, undated corporate collateral cheque for the mobilization sum", ""],
  ["B", "LASACO premium payment receipt", ""],
  ["C", "Passport photograph", ""],
  ["C", "Government-issued means of identification", ""],
  ["C", "International passport of the directors", ""],
  ["C", "Application letter to the General Manager, Lagos State PPA", ""],
  ["C", "Certificate of Incorporation, or Business Name Registration", ""],
  ["C", "CVs of key staff with relevant professional licenses/certificates", ""],
  ["C", "CAC Form 1.1 (Statement of Share Capital)", ""],
  ["C", "CAC Form 7 (Particulars of Directors) / Notice of Change of Directors", ""],
  ["C", "Memorandum and Articles of Association (MEMART)", ""],
  ["C", "Evidence of filing Annual Returns and Notice of Tax Assessment", ""],
  ["C", "3-year Personal Income Tax Clearance + Development Levy (CEO + 1 Director)", ""],
  ["C", "Company profile: structure, key personnel, similar jobs previously executed", ""],
  ["C", "(Renewal only) Previous year's PPA Registration Certificate + notarized affidavit", ""],
  ["D", "Formal Letter of Request for Balance Payment", ""],
  ["D", "Comprehensive BEFORE, DURING and AFTER pictorial and video report", ""],
  ["D", "Upgraded PPA Registration Certificate matching total contract value", ""],
  ["D", "Verified bank account details on company letterhead", ""],
  ["D", "Company Tax Identification Number (TIN)", ""],
  ["D", "Functional company email address", ""],
  ["E", "PPA Renewal for the year", "50% Advance"],
  ["E", "Tax Clearance Certificates of two directors", "50% Advance"],
  ["E", "Development Levy receipts of two directors", "50% Advance"],
  ["E", "Request letter for 50% Advance Payment", "50% Advance"],
  ["E", "Letter of Acceptance", "50% Advance"],
  ["E", "Admin fee and Agreement fee evidence", "50% Advance"],
  ["E", "Bank details on company letterhead", "50% Advance"],
  ["E", "Bond", "50% Advance"],
  ["E", "CAC Certificate", "50% Advance"],
  ["E", "Request letter for the 25% second payment", "25% at 6 months"],
  ["E", "Copy of Acceptance Letter submitted for first payment", "25% at 6 months"],
  ["E", "Bank details, CAC Certificate, PPA Renewal", "25% at 6 months"],
  ["E", "Tax Clearance and Development Levy receipts of directors", "25% at 6 months"],
  ["E", "Request letter for the 25% balance payment", "25% Balance, year-end"],
  ["E", "Copy of Acceptance Letter submitted for first payment", "25% Balance, year-end"],
  ["E", "Bank details, CAC Certificate, PPA Renewal", "25% Balance, year-end"],
  ["E", "Tax Clearance and Development Levy receipts of directors", "25% Balance, year-end"],
  ["E", "End-user report from Lascon, supporting contract renewal", "25% Balance, year-end"]
];
